package View;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import Model.MainManager;
import Model.Manager;
import Model.Subscription;
import Control.systemDataBase;

/**
 * The `LoginFrame` class creates the initial login window for the application.
 * It allows users to log in as either a Main Manager, a Regular Manager, or a Subscriber.
 * Upon successful login, it navigates to the appropriate user interface.
 */
public class LoginFrame {
    /**
     * The main method to launch the login application.
     * It sets up the login frame, input fields, and buttons,
     * and defines their action listeners for handling login attempts.
     *
     * @param args Command line arguments (not used).
     */
    public static void main(String[] args) {

        // Initialize the main login frame
        Frame loginFrame = new Frame("Login Form");
        loginFrame.setSize(400, 250);
        loginFrame.setLayout(null); // Use null layout for absolute positioning

        // Create and position the username/ID label and text field
        Label userLabel = new Label("Username / ID:");
        userLabel.setBounds(50, 60, 100, 25);
        loginFrame.add(userLabel);

        TextField userText = new TextField();
        userText.setBounds(150, 60, 180, 25);
        loginFrame.add(userText);

        // Create and position the password label and text field
        Label passLabel = new Label("Password:");
        passLabel.setBounds(50, 100, 100, 25);
        loginFrame.add(passLabel);

        TextField passText = new TextField();
        passText.setEchoChar('*'); // Mask password input
        passText.setBounds(150, 100, 180, 25);
        loginFrame.add(passText);

        // Create and position the login buttons and exit button
        Button loginButton = new Button("Login");
        loginButton.setBounds(50, 150, 80, 30);
        loginFrame.add(loginButton);

        Button subscriberLoginButton = new Button("Subscriber Login");
        subscriberLoginButton.setBounds(150, 150, 100, 30);
        loginFrame.add(subscriberLoginButton);

        Button exitButton = new Button("Exit");
        exitButton.setBounds(270, 150, 80, 30);
        loginFrame.add(exitButton);

        // Add action listener for the "Login" button
        loginButton.addActionListener(new ActionListener() {
            /**
             * Handles the action when the login button is pressed.
             * It attempts to authenticate as a Main Manager or a Regular Manager.
             * Shows appropriate dialogs for success or failure and navigates to the next frame.
             * @param e The ActionEvent generated by the button click.
             */
            public void actionPerformed(ActionEvent e) {
                String username = userText.getText();
                String password = passText.getText();

                // Attempt to log in as a Main Manager
                MainManager admin = systemDataBase.findMainManager(username, password);
                if (admin != null) {
                    loginFrame.dispose(); // Close login frame
                    MainManagerFrame.launchMainManagerPanel(); // Open Main Manager panel
                    return;
                }

                // Attempt to log in as a Regular Manager
                for (Manager m : systemDataBase.getManagers()) {
                    if (!(m instanceof MainManager) && m.getId().equals(username)) {
                        // Regular managers have a default password "1234" or no password needed if empty
                        if (password.isEmpty() || password.equals("1234")) {
                            loginFrame.dispose(); // Close login frame
                            showRegularManagerActionChoice(m); // Show choice for regular manager actions
                            return;
                        } else {
                            // Incorrect password for regular manager
                            JOptionPane.showMessageDialog(null, "Incorrect password for regular manager.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                }

                // If no manager found with provided credentials
                JOptionPane.showMessageDialog(null, "Invalid credentials or ID.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        });

        // Add action listener for the "Subscriber Login" button
        subscriberLoginButton.addActionListener(new ActionListener() {
            /**
             * Handles the action when the subscriber login button is pressed.
             * Opens a new small frame for entering a subscription code.
             * @param e The ActionEvent generated by the button click.
             */
            public void actionPerformed(ActionEvent e) {
                Frame subFrame = new Frame("Subscriber Login");
                subFrame.setSize(300, 150);
                subFrame.setLayout(null);

                Label subLabel = new Label("Enter Subscription Code:");
                subLabel.setBounds(40, 40, 150, 25);
                TextField subField = new TextField();
                subField.setBounds(190, 40, 80, 25);
                Button enterBtn = new Button("Enter");
                enterBtn.setBounds(110, 80, 80, 30);

                subFrame.add(subLabel);
                subFrame.add(subField);
                subFrame.add(enterBtn);
                subFrame.setLocationRelativeTo(null); // Center the frame
                subFrame.setVisible(true);

                // Add action listener for the "Enter" button within the subscriber login frame
                enterBtn.addActionListener(new ActionListener() {
                    /**
                     * Handles the action when the "Enter" button in the subscriber login frame is pressed.
                     * Attempts to find a matching subscription code.
                     * @param ev The ActionEvent generated by the button click.
                     */
                    public void actionPerformed(ActionEvent ev) {
                        String subCode = subField.getText().trim();
                        for (Subscription s : systemDataBase.getSubscriptions()) {
                            if (s.getSubCode().equals(subCode)) {
                                subFrame.dispose(); // Close subscriber login frame
                                loginFrame.dispose(); // Close main login frame
                                new SubscriptionPanel(s); // Open the subscriber panel
                                return;
                            }
                        }
                        // If subscription not found
                        JOptionPane.showMessageDialog(null, "Subscription not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                });
            }
        });

        // Add action listener for the "Exit" button to close the application
        exitButton.addActionListener(e -> loginFrame.dispose());

        // Load initial data for the system (e.g., predefined managers, subscriptions)
        MainManagerFrame.loadInitialData();
        // Make the login frame visible
        loginFrame.setVisible(true);
    }

    /**
     * Displays a choice frame for a regular manager to select their next action.
     * Options include adding a new order or changing a taxi in an existing order.
     *
     * @param manager The Regular Manager object that successfully logged in.
     */
    private static void showRegularManagerActionChoice(Manager manager) {
        JFrame choiceFrame = new JFrame("Choose Action");
        choiceFrame.setSize(300, 150);
        choiceFrame.setLayout(new GridLayout(3, 1)); // Use GridLayout for simple arrangement

        JLabel question = new JLabel("Select action:", SwingConstants.CENTER);
        JButton addOrderBtn = new JButton("Add New Order");
        JButton changeTaxiBtn = new JButton("Change Taxi in Order");

        // Action listener for "Add New Order" button
        addOrderBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                choiceFrame.dispose(); // Close the choice frame
                new RegularManagerFrame(manager); // Open the Regular Manager frame for adding orders
            }
        });

        // Action listener for "Change Taxi in Order" button
        changeTaxiBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                choiceFrame.dispose(); // Close the choice frame
                new ChangeTaxiFrame(manager); // Open the frame for changing taxis in orders
            }
        });

        choiceFrame.add(question);
        choiceFrame.add(addOrderBtn);
        choiceFrame.add(changeTaxiBtn);
        choiceFrame.setLocationRelativeTo(null); // Center the frame
        choiceFrame.setVisible(true);
    }
}